stages:          # List of stages for jobs, and their order of execution
  - test

run_tests:
    image: python:3.11.0
    stage: test

    before_script:
        - pip install -r requirements.txt

    script:
        - pytest --testit
