#selenium:
#  image: selenium/standalone-firefox
#  ports:
#  - 4444:4444  попробовать это, но поменять образ

version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.14.0-arsenic
    #image: retreatguru/headless-chromedriver
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-arsenic
    ports:
      - "4444:4444"